[project]
name = "littleeye"
version = "0.1.0"
description = "Peek into the structure of arbitrary nested Python objects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
numpy = ["numpy>=2"]
